[package]
name = "chess"
version = "1.0.0"
description = "A standalone chess backend for the Carp engine."
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
