[package]
name = "wasm"
version = "1.0.0"
description = "A small shim to use Carp in browsers."
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
readme = "README.md"
rust-version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
engine = { path = "../engine" }
web-time = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"