name: Build and Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v5
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Wasm-Pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -y

    - name: Build for OpenBench
      run: make

    - name: Build for WASM
      run: wasm-pack build crates/wasm --target web

    - name: Test Chess
      run: cargo test --verbose --release -p chess

    - name: Test Engine
      run: cargo test --verbose --release -p engine
